### ISSUE TITLE
Add device mapping

### ISSUE THREAD

**Issue by jw3** [jw3/feather-oled-clicker#2]
Add configurable mapping for short names

```
command: model.sh
devices:
  x0: 81cd8
  x1: 22df8
  x2: 9ebc9
  x3: 22962
  x4: e42e6
  x5: fe4c4
  x6: 89f9d
  x7: 2977b
items:
    ...
```
